server:
  port: 9100

security:
  jwt:
    public-key: classpath:public.txt
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  thymeleaf:
    prefix: classpath:/templates/
  mvc:
    view:
      suffix: .html
  main:
    allow-bean-definition-overriding: true